Repository unosquare/tubular-react, pull requests merged in 2018-02, with the labels that each got.

#70 Issue68-DataSource interface
  gulpfile.js
  package.json
  sample/src/main.tsx
  src/Grid/DataSource.ts
  src/Grid/Grid.tsx
  src/Grid/RemoteDataSource.ts
  test/Grid.spec.tsx
  test/GridToolbar.spec.tsx
  test/utils/orders.json
  test/utils/orders.ts
  typings.d.ts
Labels: Proposal

#71 Issue57 Remote data source tests
  package.json
  test/Grid.spec.tsx
  test/RemoteDataSource.spec.tsx
  test/utils/bodyRenderer.js
  test/utils/columns.js
  test/utils/columns.ts
  test/utils/data.js
  test/utils/data.ts
  test/utils/footerRenderer.js
  test/utils/orders.ts
  test/utils/requests.ts
Labels: Testing

#77 Issue73 Create column model
  sample/src/main.tsx
  src/Grid/Column.ts
  src/Grid/ColumnModel.ts
  src/Grid/DataSource.ts
  src/Grid/DateInput.tsx
  src/Grid/DialogContent.tsx
  src/Grid/DialogDropdown.tsx
  src/Grid/DialogInput.tsx
  src/Grid/Dropdown.tsx
  src/Grid/Grid.tsx
  src/Grid/GridHeader.tsx
  src/Grid/IColumnModelOptions.ts
  src/Grid/RemoteDataSource.ts
  src/Grid/TextInput.tsx
  src/Grid/index.js
  src/Grid/index.ts
Labels: enhancement

#79 Issue78 Add AppVeyor
  .travis.yml
  appveyor.yml
  gulpfile.js
  package.json
Labels: enhancement

#80 Issue74 Create class to represent grid response and grid request
  src/Grid/Grid.tsx
  src/Grid/GridRequest.ts
  src/Grid/GridResponse.ts
  src/Grid/RemoteDataSource.ts
  test/Grid.spec.tsx
  test/RemoteDataSource.spec.tsx
  test/utils/columns.ts
  test/utils/requests.ts
Labels: enhancement

#90 Issue 64 - Local DataSource Unit Testing
  test/DataGrid.spec.tsx
  test/LocalDataSource.spec.tsx
  test/utils/LocalDataSourceMocks.ts
  test/utils/columns.ts
  test/utils/data.ts
  test/utils/localData.ts
Labels: enhancement

#97 Issue95-Issue91-Unit test: Column string (case: Contains)
  src/Grid/LocalDataSource.ts
  test/LocalDataSource.spec.tsx
  test/utils/LocalDataSourceMocks.ts
Labels: Testing

#149 Refactor on Data Source elements.
  sample/src/local/main.tsx
  src/DataGrid/BaseDataSource.ts
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataSource.ts
  src/DataGrid/LocalDataSource.ts
  src/DataGrid/RemoteDataSource.ts
  test/RemoteDataSource.spec.tsx
Labels: enhancement
