Repository unosquare/tubular-react, pull requests merged in 2019-08, with the labels that each got.

#360 Added Storage Section
  docs/index.html
  docs/pages.ccee3f7c.js
  srcdocs/components/CustomizableGrid.tsx
  srcdocs/components/Navigation.tsx
  srcdocs/pages/Documentation/Features/Storage.tsx
  srcdocs/pages/Main.tsx
  srcdocs/utils/featuresPaths.ts
  srcdocs/utils/storageCodeSamples.ts
Labels: documentation

#387 Proposal for refreshing grid
  sample/src/localDataGrid.tsx
  sample/src/remoteDataGrid.tsx
  src/DataGrid/DataGrid.tsx
  src/Hooks/index.ts
  src/Hooks/useDataGrid.ts
  src/Hooks/useGridRefresh.ts
Labels: enhancement

#389 Fixed export on Hooks
  src/index.ts
Labels: bug

#396 Added missing param on bodyRenderer signature for some components
  sample/src/remoteDataGrid.tsx
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridTable.tsx
  src/DataGrid/GridBody.tsx
Labels: bug
