Repository unosquare/tubular-react, pull requests merged in 2019-07, with the labels that each got.

#325 Issue321 responsive grid
  package-lock.json
  package.json
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridCard.tsx
  src/DataGrid/GridToolbar.tsx
  src/DataGrid/Paginator.tsx
  src/DataGrid/index.ts
Labels: enhancement

#326 Fixing improper use of makeStyles
  package-lock.json
  src/DataGrid/AdvancePaginationActions.tsx
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridCard.tsx
  src/DataGrid/Paginator.tsx
  src/Implementations/DataGridWithRemoteDataSource.tsx
  srcdocs/components/ColumnModelTable.tsx
  srcdocs/components/DataGridProps.tsx
  srcdocs/components/DataGridProviderProps.tsx
  srcdocs/components/DataGridTableProps.tsx
  srcdocs/components/ToolBarOptionsProps.tsx
  srcdocs/pages/Documentation/ComponentAPI.tsx
  srcdocs/pages/Documentation/Home.tsx
Labels: bug

#328 Removing entire folder
  sample/src/DataGridWithDialog.tsx
  sample/src/main.tsx
  src/Implementations/DataGridWithRemoteDataSource.tsx
  src/Implementations/index.ts
  src/index.ts
Labels: enhancement

#333 Considering limit for pages.
  docs/index.html
  docs/pages.9332cc3d.js
  src/DataSource/BaseDataSource.tsx
  src/DataSource/LocalDataSource.ts
  src/DataSource/RemoteDataSource.ts
Labels: bug

#334 Hackathon fix
  src/DataSource/BaseDataSource.tsx
Labels: bug

#335 Hooks refactor
  package-lock.json
  package.json
  sample/src/CustomLayoutDataGrid.tsx
  sample/src/RemoteGridList.tsx
  sample/src/localDataGrid.tsx
  sample/src/remoteDataGrid.tsx
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridContext.tsx
  src/DataGrid/DataGridTable.tsx
  src/DataGrid/DialogModal.tsx
  src/DataGrid/GridBody.tsx
  src/DataGrid/GridHeader.tsx
  src/DataGrid/GridToolbar.tsx
  src/DataGrid/SearchTextInput.tsx
  src/DataGrid/index.ts
  src/DataGridInterfaces/IDataGrid.ts
  src/DataGridInterfaces/IDataGridApi.ts
  src/DataGridInterfaces/IDataGridProps.ts
  src/DataGridInterfaces/IDataGridState.ts
  src/DataGridInterfaces/IDataGridStorage.ts
  src/DataGridInterfaces/IFilterWrapper.ts
  src/DataGridInterfaces/index.ts
  src/DataSource/BaseDataSource.tsx
  src/DataSource/DataSourceContext.ts
  src/DataSource/IBaseDataSourceState.ts
  src/DataSource/LocalDataSource.ts
  src/DataSource/RemoteDataSource.ts
  src/DataSource/index.ts
  src/Filtering/DialogInput.tsx
  src/Filtering/DialogModal.tsx
  src/Filtering/OperatorsDropdown.tsx
  src/Filtering/SearchTextInput.tsx
  src/Filtering/index.ts
  src/Hooks/useDataGrid.ts
  src/Models/index.ts
  src/Pagination/AdvancePaginationActions.tsx
  src/Pagination/Paginator.tsx
  src/Pagination/index.ts
  src/Storage/LocalStorage.tsx
  src/Storage/NullStorage.tsx
  src/Storage/index.ts
  src/Toolbar/ExportButton.tsx
  src/Toolbar/GridToolbar.tsx
  src/Toolbar/GridToolbarFunctions.ts
  src/Toolbar/ToolbarOptions.ts
  src/Toolbar/index.ts
  src/index.ts
  test/LocalDataSource.spec.tsx
  test/useDataGrid.spec.tsx
  test/utils/testHook.tsx
  test/utils/utils.tsx
Labels: Proposal

#339 Changed docs structure
  docs/index.html
  docs/pages.00ef3026.js
  docs/tubular.65203470.png
  package-lock.json
  package.json
  src/DataGrid/DataGrid.tsx
  srcdocs/components/BasicFeatures.tsx
  srcdocs/components/FeatureSample.tsx
  srcdocs/components/Navigation.tsx
  srcdocs/components/NavigationBar.tsx
  srcdocs/components/Pagination/AdvancedPaginationGrid.tsx
  srcdocs/components/Pagination/BasicPaginationGrid.tsx
  srcdocs/components/SampleButtonsFeatures.tsx
  srcdocs/components/SampleFeatures.tsx
  srcdocs/components/SampleGridList.tsx
  srcdocs/components/TableOfContent.tsx
  srcdocs/components/ToolBarOptionsProps.tsx
  srcdocs/index.html
  srcdocs/pages/Documentation/ComponentAPI.tsx
  srcdocs/pages/Documentation/Features/Pagination.tsx
  srcdocs/pages/Documentation/Home.tsx
  srcdocs/pages/Documentation/Sample.tsx
  srcdocs/pages/Index.tsx
  srcdocs/pages/Main.tsx
  srcdocs/utils/codeSnipetExamples.ts
Labels: documentation

#345 Changed Component to block UI on loading
  docs/date-fns.78674abe.js
  docs/date-fns.be170294.js
  docs/favicon.e533d247.ico
  docs/index.html
  docs/index.js
  docs/lib.30250b8a.js
  docs/lib.50777e08.js
  docs/pages.00ef3026.js
  docs/pages.1396a611.css
  docs/pages.1396a611.js
  docs/pages.750df968.css
  docs/react-dom.993dbee1.js
  docs/react-dom.bd9c01eb.js
  docs/react-highlight.0756b5ef.js
  docs/react-highlight.989d87e3.js
  docs/react.7f931882.js
  docs/react.cbca72c4.js
  docs/tubular.53a91bf7.png
  src/Pagination/AdvancePaginationActions.tsx
  src/Pagination/Paginator.tsx
Labels: bug

#347 Adding TableSortLabel instead of custom icon
  src/DataGrid/GridHeader.tsx
Labels: enhancement

#349 Removal of anchor filter from grid state. Fixing multiple bugs
  src/DataGrid/GridHeader.tsx
  src/DataGridInterfaces/IDataGridApi.ts
  src/DataGridInterfaces/IDataGridState.ts
  src/Filtering/DialogModal.tsx
  src/Hooks/useDataGrid.ts
  src/Pagination/Paginator.tsx
  test/useDataGrid.spec.tsx
Labels: bug, enhancement

#350 Added Toolbar section to docs
  docs/index.html
  docs/pages.daa66bae.js
  srcdocs/components/CustomizableGrid.tsx
  srcdocs/components/FeatureSample.tsx
  srcdocs/components/Navigation.tsx
  srcdocs/components/Options/Pagination.tsx
  srcdocs/components/Options/Toolbar.tsx
  srcdocs/components/Pagination/AdvancedPaginationGrid.tsx
  srcdocs/components/Pagination/BasicPaginationGrid.tsx
  srcdocs/pages/Documentation/Features/Pagination.tsx
  srcdocs/pages/Documentation/Features/Toolbar.tsx
  srcdocs/pages/Main.tsx
  srcdocs/utils/codeSnipetExamples.ts
  srcdocs/utils/columns.ts
  srcdocs/utils/featuresStyles.ts
  srcdocs/utils/paginationCodeSamples.ts
  srcdocs/utils/toolbarCodeSamples.ts
Labels: documentation

#351 Better usage of types
  sample/src/localDataGrid.tsx
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridCard.tsx
  src/DataGrid/DataGridTable.tsx
  src/DataGrid/GridBody.tsx
  src/DataGrid/GridHeader.tsx
  src/DataGridInterfaces/IDataGridApi.ts
  src/DataGridInterfaces/IDataGridConfig.ts
  src/DataGridInterfaces/IDataGridState.ts
  src/Filtering/DialogInput.tsx
  src/Filtering/DialogModal.tsx
  src/Filtering/SearchTextInput.tsx
  src/Hooks/useDataGrid.ts
  src/Pagination/AdvancePaginationActions.tsx
  src/Pagination/Paginator.tsx
  src/Toolbar/ExportButton.tsx
  src/Toolbar/GridToolbar.tsx
  src/Toolbar/ToolbarOptions.ts
Labels: enhancement

#353 [FIX] Removed children from mobile toolbar
  src/DataGrid/DataGrid.tsx
Labels: bug

#354 Added Toolbar package to exports on index.ts
  src/Toolbar/index.ts
  src/index.ts
Labels: bug

#355 Unit test poc
  package-lock.json
  package.json
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridTable.tsx
  src/DataGrid/GridBody.tsx
  src/DataGridInterfaces/IDataGridConfig.ts
  src/Hooks/useDataGrid.ts
  src/Toolbar/GridToolbar.tsx
  src/Toolbar/ToolbarOptions.ts
  test/AdvancePaginationActions.spec.tsx
  test/DataGrid.spec.tsx
  test/GridHeader.spec.tsx
  test/GridToolbar.spec.tsx
  test/LocalDataSource.spec.tsx
  test/RemoteDataSource.spec.tsx
  test/setupTest.js
  test/useDataGrid.spec.tsx
  test/utils/mockContext.ts
  test/utils/testHook.tsx
Labels: bug, enhancement

#356 Fixed event onRowClick and added a sample on localDataGrid
  package.json
  sample/src/localDataGrid.tsx
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridTable.tsx
  src/DataGrid/GridBody.tsx
Labels: bug

#358 Update README.md
  README.md
Labels: documentation
