Repository unosquare/tubular-react, pull requests merged in 2020-06, with the labels that each got.

#790 Fix: deps upgrade
  package-lock.json
  package.json
Labels: enhancement

#800 Update @material-ui/pickers to 4.0.0-alpha.8
  package-lock.json
  package.json
  src/Filtering/DateFilter.tsx
Labels: enhancement

#810 Fix next buttons with no records found
  src/Pagination/AdvancePaginationActions.tsx
Labels: bug

#826 Feature: Row selection
  .eslintrc.js
  package-lock.json
  package.json
  sample/src/localDataGrid.tsx
  sample/src/remoteDataGrid.tsx
  src/BareBones/TbRow.tsx
  src/DataGrid/DataGrid.tsx
  src/DataGrid/DataGridTable.tsx
  src/DataGrid/GridBody.tsx
  src/DataGrid/GridHeader.tsx
  src/Filtering/StandardFilterEditor.tsx
  src/Toolbar/SelectionToolbar.tsx
  src/Toolbar/ToolbarOptions.ts
  src/hooks/useTbSelection.ts
  src/utils/Selection.ts
Labels: enhancement

#815 ReadMe
  README.md
Labels: documentation

#830 bug: Fix problem with MUI imports
  .eslintrc.js
  package.json
  src/BareBones/TbRow.tsx
  src/DataGrid/NoDataRow.tsx
  src/Pagination/Paginator.tsx
Labels: bug
