Repository unosquare/tubular-react, pull requests merged in 2020-01, with the labels that each got.

#604 Fixes filtering issue due to wrong case when handling filter change
  src/Filtering/DialogModal.tsx
Labels: bug

#605 Fixes issue with filtering for local data source
  package-lock.json
  package.json
Labels: dependencies

#608 Added Language service
  README.md
  package-lock.json
  package.json
  src/DataGrid/GridHeaderCell.tsx
  src/DataGrid/NoDataRow.tsx
  src/Filtering/DialogInput.tsx
  src/Filtering/OperatorsDropdown.tsx
  src/Pagination/AdvancePaginationActions.tsx
  src/Pagination/Paginator.tsx
  src/TbList/TbList.tsx
  src/Toolbar/ExportButton.tsx
  src/utils/Lang.ts
  src/utils/index.ts
  src/utils/languages/English.ts
  src/utils/languages/TubularLangDef.ts
  test/LanguageService.spec.ts
  tsconfig.json
Labels: enhancement
